/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteQuemSomosRouteImport } from './routes/_site.quem-somos'
import { Route as SitePremiacoesRouteImport } from './routes/_site.premiacoes'
import { Route as SiteNaMidiaRouteImport } from './routes/_site.na-midia'
import { Route as SiteContatoRouteImport } from './routes/_site.contato'
import { Route as SiteCasosDeSucessoRouteImport } from './routes/_site.casos-de-sucesso'
import { Route as SiteBlogRouteImport } from './routes/_site.blog'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as SiteEsIndexRouteImport } from './routes/_site.es.index'
import { Route as SiteEquipeIndexRouteImport } from './routes/_site.equipe.index'
import { Route as SiteEnIndexRouteImport } from './routes/_site.en.index'
import { Route as SiteAreasDeAtuacaoIndexRouteImport } from './routes/_site.areas-de-atuacao.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as SiteEsQuemSomosRouteImport } from './routes/_site.es.quem-somos'
import { Route as SiteEsPremiacoesRouteImport } from './routes/_site.es.premiacoes'
import { Route as SiteEsNaMidiaRouteImport } from './routes/_site.es.na-midia'
import { Route as SiteEsContatoRouteImport } from './routes/_site.es.contato'
import { Route as SiteEsCasosDeSucessoRouteImport } from './routes/_site.es.casos-de-sucesso'
import { Route as SiteEsBlogRouteImport } from './routes/_site.es.blog'
import { Route as SiteEquipeSlugRouteImport } from './routes/_site.equipe.$slug'
import { Route as SiteEnQuemSomosRouteImport } from './routes/_site.en.quem-somos'
import { Route as SiteEnPremiacoesRouteImport } from './routes/_site.en.premiacoes'
import { Route as SiteEnNaMidiaRouteImport } from './routes/_site.en.na-midia'
import { Route as SiteEnContatoRouteImport } from './routes/_site.en.contato'
import { Route as SiteEnCasosDeSucessoRouteImport } from './routes/_site.en.casos-de-sucesso'
import { Route as SiteEnBlogRouteImport } from './routes/_site.en.blog'
import { Route as SiteBlogBuscaRouteImport } from './routes/_site.blog.busca'
import { Route as SiteBlogSlugRouteImport } from './routes/_site.blog.$slug'
import { Route as SiteAreasDeAtuacaoSlugRouteImport } from './routes/_site.areas-de-atuacao.$slug'
import { Route as AuthenticatedAdminTagsRouteImport } from './routes/_authenticated/admin/tags'
import { Route as AuthenticatedAdminSeoRouteImport } from './routes/_authenticated/admin/seo'
import { Route as AuthenticatedAdminProfissoesRouteImport } from './routes/_authenticated/admin/profissoes'
import { Route as AuthenticatedAdminMidiaRouteImport } from './routes/_authenticated/admin/midia'
import { Route as AuthenticatedAdminEquipeRouteImport } from './routes/_authenticated/admin/equipe'
import { Route as AuthenticatedAdminCategoriasRouteImport } from './routes/_authenticated/admin/categorias'
import { Route as AuthenticatedAdminAutoresRouteImport } from './routes/_authenticated/admin/autores'
import { Route as SiteEsServicosIndexRouteImport } from './routes/_site.es.servicos.index'
import { Route as SiteEsEquipeIndexRouteImport } from './routes/_site.es.equipe.index'
import { Route as SiteEnServicosIndexRouteImport } from './routes/_site.en.servicos.index'
import { Route as SiteEnEquipeIndexRouteImport } from './routes/_site.en.equipe.index'
import { Route as AuthenticatedAdminPostsIndexRouteImport } from './routes/_authenticated/admin/posts/index'
import { Route as SiteEsServicosSlugRouteImport } from './routes/_site.es.servicos.$slug'
import { Route as SiteEsEquipeSlugRouteImport } from './routes/_site.es.equipe.$slug'
import { Route as SiteEsBlogBusquedaRouteImport } from './routes/_site.es.blog.busqueda'
import { Route as SiteEsBlogSlugRouteImport } from './routes/_site.es.blog.$slug'
import { Route as SiteEnServicosSlugRouteImport } from './routes/_site.en.servicos.$slug'
import { Route as SiteEnEquipeSlugRouteImport } from './routes/_site.en.equipe.$slug'
import { Route as SiteEnBlogSearchRouteImport } from './routes/_site.en.blog.search'
import { Route as SiteEnBlogSlugRouteImport } from './routes/_site.en.blog.$slug'
import { Route as SiteBlogTagSlugRouteImport } from './routes/_site.blog.tag.$slug'
import { Route as SiteBlogProfissaoSlugRouteImport } from './routes/_site.blog.profissao.$slug'
import { Route as SiteBlogCategoriaSlugRouteImport } from './routes/_site.blog.categoria.$slug'
import { Route as SiteBlogAutorSlugRouteImport } from './routes/_site.blog.autor.$slug'
import { Route as AuthenticatedAdminPostsNovoRouteImport } from './routes/_authenticated/admin/posts/novo'
import { Route as AuthenticatedAdminPostsDestaquesRouteImport } from './routes/_authenticated/admin/posts/destaques'
import { Route as AuthenticatedAdminPostsIdRouteImport } from './routes/_authenticated/admin/posts/$id'
import { Route as SiteEsBlogTagSlugRouteImport } from './routes/_site.es.blog.tag.$slug'
import { Route as SiteEsBlogProfesionSlugRouteImport } from './routes/_site.es.blog.profesion.$slug'
import { Route as SiteEsBlogCategoriaSlugRouteImport } from './routes/_site.es.blog.categoria.$slug'
import { Route as SiteEsBlogAutorSlugRouteImport } from './routes/_site.es.blog.autor.$slug'
import { Route as SiteEnBlogTagSlugRouteImport } from './routes/_site.en.blog.tag.$slug'
import { Route as SiteEnBlogProfessionSlugRouteImport } from './routes/_site.en.blog.profession.$slug'
import { Route as SiteEnBlogCategorySlugRouteImport } from './routes/_site.en.blog.category.$slug'
import { Route as SiteEnBlogAuthorSlugRouteImport } from './routes/_site.en.blog.author.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteQuemSomosRoute = SiteQuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => SiteRoute,
} as any)
const SitePremiacoesRoute = SitePremiacoesRouteImport.update({
  id: '/premiacoes',
  path: '/premiacoes',
  getParentRoute: () => SiteRoute,
} as any)
const SiteNaMidiaRoute = SiteNaMidiaRouteImport.update({
  id: '/na-midia',
  path: '/na-midia',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContatoRoute = SiteContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCasosDeSucessoRoute = SiteCasosDeSucessoRouteImport.update({
  id: '/casos-de-sucesso',
  path: '/casos-de-sucesso',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogRoute = SiteBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => SiteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SiteEsIndexRoute = SiteEsIndexRouteImport.update({
  id: '/es/',
  path: '/es/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEquipeIndexRoute = SiteEquipeIndexRouteImport.update({
  id: '/equipe/',
  path: '/equipe/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEnIndexRoute = SiteEnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAreasDeAtuacaoIndexRoute = SiteAreasDeAtuacaoIndexRouteImport.update({
  id: '/areas-de-atuacao/',
  path: '/areas-de-atuacao/',
  getParentRoute: () => SiteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const SiteEsQuemSomosRoute = SiteEsQuemSomosRouteImport.update({
  id: '/es/quem-somos',
  path: '/es/quem-somos',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEsPremiacoesRoute = SiteEsPremiacoesRouteImport.update({
  id: '/es/premiacoes',
  path: '/es/premiacoes',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEsNaMidiaRoute = SiteEsNaMidiaRouteImport.update({
  id: '/es/na-midia',
  path: '/es/na-midia',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEsContatoRoute = SiteEsContatoRouteImport.update({
  id: '/es/contato',
  path: '/es/contato',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEsCasosDeSucessoRoute = SiteEsCasosDeSucessoRouteImport.update({
  id: '/es/casos-de-sucesso',
  path: '/es/casos-de-sucesso',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEsBlogRoute = SiteEsBlogRouteImport.update({
  id: '/es/blog',
  path: '/es/blog',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEquipeSlugRoute = SiteEquipeSlugRouteImport.update({
  id: '/equipe/$slug',
  path: '/equipe/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEnQuemSomosRoute = SiteEnQuemSomosRouteImport.update({
  id: '/en/quem-somos',
  path: '/en/quem-somos',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEnPremiacoesRoute = SiteEnPremiacoesRouteImport.update({
  id: '/en/premiacoes',
  path: '/en/premiacoes',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEnNaMidiaRoute = SiteEnNaMidiaRouteImport.update({
  id: '/en/na-midia',
  path: '/en/na-midia',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEnContatoRoute = SiteEnContatoRouteImport.update({
  id: '/en/contato',
  path: '/en/contato',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEnCasosDeSucessoRoute = SiteEnCasosDeSucessoRouteImport.update({
  id: '/en/casos-de-sucesso',
  path: '/en/casos-de-sucesso',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEnBlogRoute = SiteEnBlogRouteImport.update({
  id: '/en/blog',
  path: '/en/blog',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogBuscaRoute = SiteBlogBuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => SiteBlogRoute,
} as any)
const SiteBlogSlugRoute = SiteBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SiteBlogRoute,
} as any)
const SiteAreasDeAtuacaoSlugRoute = SiteAreasDeAtuacaoSlugRouteImport.update({
  id: '/areas-de-atuacao/$slug',
  path: '/areas-de-atuacao/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const AuthenticatedAdminTagsRoute = AuthenticatedAdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSeoRoute = AuthenticatedAdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminProfissoesRoute =
  AuthenticatedAdminProfissoesRouteImport.update({
    id: '/profissoes',
    path: '/profissoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMidiaRoute = AuthenticatedAdminMidiaRouteImport.update({
  id: '/midia',
  path: '/midia',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminEquipeRoute =
  AuthenticatedAdminEquipeRouteImport.update({
    id: '/equipe',
    path: '/equipe',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCategoriasRoute =
  AuthenticatedAdminCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAutoresRoute =
  AuthenticatedAdminAutoresRouteImport.update({
    id: '/autores',
    path: '/autores',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const SiteEsServicosIndexRoute = SiteEsServicosIndexRouteImport.update({
  id: '/es/servicos/',
  path: '/es/servicos/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEsEquipeIndexRoute = SiteEsEquipeIndexRouteImport.update({
  id: '/es/equipe/',
  path: '/es/equipe/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEnServicosIndexRoute = SiteEnServicosIndexRouteImport.update({
  id: '/en/servicos/',
  path: '/en/servicos/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEnEquipeIndexRoute = SiteEnEquipeIndexRouteImport.update({
  id: '/en/equipe/',
  path: '/en/equipe/',
  getParentRoute: () => SiteRoute,
} as any)
const AuthenticatedAdminPostsIndexRoute =
  AuthenticatedAdminPostsIndexRouteImport.update({
    id: '/posts/',
    path: '/posts/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const SiteEsServicosSlugRoute = SiteEsServicosSlugRouteImport.update({
  id: '/es/servicos/$slug',
  path: '/es/servicos/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEsEquipeSlugRoute = SiteEsEquipeSlugRouteImport.update({
  id: '/es/equipe/$slug',
  path: '/es/equipe/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEsBlogBusquedaRoute = SiteEsBlogBusquedaRouteImport.update({
  id: '/busqueda',
  path: '/busqueda',
  getParentRoute: () => SiteEsBlogRoute,
} as any)
const SiteEsBlogSlugRoute = SiteEsBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SiteEsBlogRoute,
} as any)
const SiteEnServicosSlugRoute = SiteEnServicosSlugRouteImport.update({
  id: '/en/servicos/$slug',
  path: '/en/servicos/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEnEquipeSlugRoute = SiteEnEquipeSlugRouteImport.update({
  id: '/en/equipe/$slug',
  path: '/en/equipe/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEnBlogSearchRoute = SiteEnBlogSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => SiteEnBlogRoute,
} as any)
const SiteEnBlogSlugRoute = SiteEnBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SiteEnBlogRoute,
} as any)
const SiteBlogTagSlugRoute = SiteBlogTagSlugRouteImport.update({
  id: '/tag/$slug',
  path: '/tag/$slug',
  getParentRoute: () => SiteBlogRoute,
} as any)
const SiteBlogProfissaoSlugRoute = SiteBlogProfissaoSlugRouteImport.update({
  id: '/profissao/$slug',
  path: '/profissao/$slug',
  getParentRoute: () => SiteBlogRoute,
} as any)
const SiteBlogCategoriaSlugRoute = SiteBlogCategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => SiteBlogRoute,
} as any)
const SiteBlogAutorSlugRoute = SiteBlogAutorSlugRouteImport.update({
  id: '/autor/$slug',
  path: '/autor/$slug',
  getParentRoute: () => SiteBlogRoute,
} as any)
const AuthenticatedAdminPostsNovoRoute =
  AuthenticatedAdminPostsNovoRouteImport.update({
    id: '/posts/novo',
    path: '/posts/novo',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPostsDestaquesRoute =
  AuthenticatedAdminPostsDestaquesRouteImport.update({
    id: '/posts/destaques',
    path: '/posts/destaques',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPostsIdRoute =
  AuthenticatedAdminPostsIdRouteImport.update({
    id: '/posts/$id',
    path: '/posts/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const SiteEsBlogTagSlugRoute = SiteEsBlogTagSlugRouteImport.update({
  id: '/tag/$slug',
  path: '/tag/$slug',
  getParentRoute: () => SiteEsBlogRoute,
} as any)
const SiteEsBlogProfesionSlugRoute = SiteEsBlogProfesionSlugRouteImport.update({
  id: '/profesion/$slug',
  path: '/profesion/$slug',
  getParentRoute: () => SiteEsBlogRoute,
} as any)
const SiteEsBlogCategoriaSlugRoute = SiteEsBlogCategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => SiteEsBlogRoute,
} as any)
const SiteEsBlogAutorSlugRoute = SiteEsBlogAutorSlugRouteImport.update({
  id: '/autor/$slug',
  path: '/autor/$slug',
  getParentRoute: () => SiteEsBlogRoute,
} as any)
const SiteEnBlogTagSlugRoute = SiteEnBlogTagSlugRouteImport.update({
  id: '/tag/$slug',
  path: '/tag/$slug',
  getParentRoute: () => SiteEnBlogRoute,
} as any)
const SiteEnBlogProfessionSlugRoute =
  SiteEnBlogProfessionSlugRouteImport.update({
    id: '/profession/$slug',
    path: '/profession/$slug',
    getParentRoute: () => SiteEnBlogRoute,
  } as any)
const SiteEnBlogCategorySlugRoute = SiteEnBlogCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => SiteEnBlogRoute,
} as any)
const SiteEnBlogAuthorSlugRoute = SiteEnBlogAuthorSlugRouteImport.update({
  id: '/author/$slug',
  path: '/author/$slug',
  getParentRoute: () => SiteEnBlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/blog': typeof SiteBlogRouteWithChildren
  '/casos-de-sucesso': typeof SiteCasosDeSucessoRoute
  '/contato': typeof SiteContatoRoute
  '/na-midia': typeof SiteNaMidiaRoute
  '/premiacoes': typeof SitePremiacoesRoute
  '/quem-somos': typeof SiteQuemSomosRoute
  '/admin/autores': typeof AuthenticatedAdminAutoresRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/admin/midia': typeof AuthenticatedAdminMidiaRoute
  '/admin/profissoes': typeof AuthenticatedAdminProfissoesRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/areas-de-atuacao/$slug': typeof SiteAreasDeAtuacaoSlugRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/blog/busca': typeof SiteBlogBuscaRoute
  '/en/blog': typeof SiteEnBlogRouteWithChildren
  '/en/casos-de-sucesso': typeof SiteEnCasosDeSucessoRoute
  '/en/contato': typeof SiteEnContatoRoute
  '/en/na-midia': typeof SiteEnNaMidiaRoute
  '/en/premiacoes': typeof SiteEnPremiacoesRoute
  '/en/quem-somos': typeof SiteEnQuemSomosRoute
  '/equipe/$slug': typeof SiteEquipeSlugRoute
  '/es/blog': typeof SiteEsBlogRouteWithChildren
  '/es/casos-de-sucesso': typeof SiteEsCasosDeSucessoRoute
  '/es/contato': typeof SiteEsContatoRoute
  '/es/na-midia': typeof SiteEsNaMidiaRoute
  '/es/premiacoes': typeof SiteEsPremiacoesRoute
  '/es/quem-somos': typeof SiteEsQuemSomosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/areas-de-atuacao/': typeof SiteAreasDeAtuacaoIndexRoute
  '/en/': typeof SiteEnIndexRoute
  '/equipe/': typeof SiteEquipeIndexRoute
  '/es/': typeof SiteEsIndexRoute
  '/admin/posts/$id': typeof AuthenticatedAdminPostsIdRoute
  '/admin/posts/destaques': typeof AuthenticatedAdminPostsDestaquesRoute
  '/admin/posts/novo': typeof AuthenticatedAdminPostsNovoRoute
  '/blog/autor/$slug': typeof SiteBlogAutorSlugRoute
  '/blog/categoria/$slug': typeof SiteBlogCategoriaSlugRoute
  '/blog/profissao/$slug': typeof SiteBlogProfissaoSlugRoute
  '/blog/tag/$slug': typeof SiteBlogTagSlugRoute
  '/en/blog/$slug': typeof SiteEnBlogSlugRoute
  '/en/blog/search': typeof SiteEnBlogSearchRoute
  '/en/equipe/$slug': typeof SiteEnEquipeSlugRoute
  '/en/servicos/$slug': typeof SiteEnServicosSlugRoute
  '/es/blog/$slug': typeof SiteEsBlogSlugRoute
  '/es/blog/busqueda': typeof SiteEsBlogBusquedaRoute
  '/es/equipe/$slug': typeof SiteEsEquipeSlugRoute
  '/es/servicos/$slug': typeof SiteEsServicosSlugRoute
  '/admin/posts/': typeof AuthenticatedAdminPostsIndexRoute
  '/en/equipe/': typeof SiteEnEquipeIndexRoute
  '/en/servicos/': typeof SiteEnServicosIndexRoute
  '/es/equipe/': typeof SiteEsEquipeIndexRoute
  '/es/servicos/': typeof SiteEsServicosIndexRoute
  '/en/blog/author/$slug': typeof SiteEnBlogAuthorSlugRoute
  '/en/blog/category/$slug': typeof SiteEnBlogCategorySlugRoute
  '/en/blog/profession/$slug': typeof SiteEnBlogProfessionSlugRoute
  '/en/blog/tag/$slug': typeof SiteEnBlogTagSlugRoute
  '/es/blog/autor/$slug': typeof SiteEsBlogAutorSlugRoute
  '/es/blog/categoria/$slug': typeof SiteEsBlogCategoriaSlugRoute
  '/es/blog/profesion/$slug': typeof SiteEsBlogProfesionSlugRoute
  '/es/blog/tag/$slug': typeof SiteEsBlogTagSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof SiteIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog': typeof SiteBlogRouteWithChildren
  '/casos-de-sucesso': typeof SiteCasosDeSucessoRoute
  '/contato': typeof SiteContatoRoute
  '/na-midia': typeof SiteNaMidiaRoute
  '/premiacoes': typeof SitePremiacoesRoute
  '/quem-somos': typeof SiteQuemSomosRoute
  '/admin/autores': typeof AuthenticatedAdminAutoresRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/admin/midia': typeof AuthenticatedAdminMidiaRoute
  '/admin/profissoes': typeof AuthenticatedAdminProfissoesRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/areas-de-atuacao/$slug': typeof SiteAreasDeAtuacaoSlugRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/blog/busca': typeof SiteBlogBuscaRoute
  '/en/blog': typeof SiteEnBlogRouteWithChildren
  '/en/casos-de-sucesso': typeof SiteEnCasosDeSucessoRoute
  '/en/contato': typeof SiteEnContatoRoute
  '/en/na-midia': typeof SiteEnNaMidiaRoute
  '/en/premiacoes': typeof SiteEnPremiacoesRoute
  '/en/quem-somos': typeof SiteEnQuemSomosRoute
  '/equipe/$slug': typeof SiteEquipeSlugRoute
  '/es/blog': typeof SiteEsBlogRouteWithChildren
  '/es/casos-de-sucesso': typeof SiteEsCasosDeSucessoRoute
  '/es/contato': typeof SiteEsContatoRoute
  '/es/na-midia': typeof SiteEsNaMidiaRoute
  '/es/premiacoes': typeof SiteEsPremiacoesRoute
  '/es/quem-somos': typeof SiteEsQuemSomosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/areas-de-atuacao': typeof SiteAreasDeAtuacaoIndexRoute
  '/en': typeof SiteEnIndexRoute
  '/equipe': typeof SiteEquipeIndexRoute
  '/es': typeof SiteEsIndexRoute
  '/admin/posts/$id': typeof AuthenticatedAdminPostsIdRoute
  '/admin/posts/destaques': typeof AuthenticatedAdminPostsDestaquesRoute
  '/admin/posts/novo': typeof AuthenticatedAdminPostsNovoRoute
  '/blog/autor/$slug': typeof SiteBlogAutorSlugRoute
  '/blog/categoria/$slug': typeof SiteBlogCategoriaSlugRoute
  '/blog/profissao/$slug': typeof SiteBlogProfissaoSlugRoute
  '/blog/tag/$slug': typeof SiteBlogTagSlugRoute
  '/en/blog/$slug': typeof SiteEnBlogSlugRoute
  '/en/blog/search': typeof SiteEnBlogSearchRoute
  '/en/equipe/$slug': typeof SiteEnEquipeSlugRoute
  '/en/servicos/$slug': typeof SiteEnServicosSlugRoute
  '/es/blog/$slug': typeof SiteEsBlogSlugRoute
  '/es/blog/busqueda': typeof SiteEsBlogBusquedaRoute
  '/es/equipe/$slug': typeof SiteEsEquipeSlugRoute
  '/es/servicos/$slug': typeof SiteEsServicosSlugRoute
  '/admin/posts': typeof AuthenticatedAdminPostsIndexRoute
  '/en/equipe': typeof SiteEnEquipeIndexRoute
  '/en/servicos': typeof SiteEnServicosIndexRoute
  '/es/equipe': typeof SiteEsEquipeIndexRoute
  '/es/servicos': typeof SiteEsServicosIndexRoute
  '/en/blog/author/$slug': typeof SiteEnBlogAuthorSlugRoute
  '/en/blog/category/$slug': typeof SiteEnBlogCategorySlugRoute
  '/en/blog/profession/$slug': typeof SiteEnBlogProfessionSlugRoute
  '/en/blog/tag/$slug': typeof SiteEnBlogTagSlugRoute
  '/es/blog/autor/$slug': typeof SiteEsBlogAutorSlugRoute
  '/es/blog/categoria/$slug': typeof SiteEsBlogCategoriaSlugRoute
  '/es/blog/profesion/$slug': typeof SiteEsBlogProfesionSlugRoute
  '/es/blog/tag/$slug': typeof SiteEsBlogTagSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_site/blog': typeof SiteBlogRouteWithChildren
  '/_site/casos-de-sucesso': typeof SiteCasosDeSucessoRoute
  '/_site/contato': typeof SiteContatoRoute
  '/_site/na-midia': typeof SiteNaMidiaRoute
  '/_site/premiacoes': typeof SitePremiacoesRoute
  '/_site/quem-somos': typeof SiteQuemSomosRoute
  '/_site/': typeof SiteIndexRoute
  '/_authenticated/admin/autores': typeof AuthenticatedAdminAutoresRoute
  '/_authenticated/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/_authenticated/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/_authenticated/admin/midia': typeof AuthenticatedAdminMidiaRoute
  '/_authenticated/admin/profissoes': typeof AuthenticatedAdminProfissoesRoute
  '/_authenticated/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/_authenticated/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/_site/areas-de-atuacao/$slug': typeof SiteAreasDeAtuacaoSlugRoute
  '/_site/blog/$slug': typeof SiteBlogSlugRoute
  '/_site/blog/busca': typeof SiteBlogBuscaRoute
  '/_site/en/blog': typeof SiteEnBlogRouteWithChildren
  '/_site/en/casos-de-sucesso': typeof SiteEnCasosDeSucessoRoute
  '/_site/en/contato': typeof SiteEnContatoRoute
  '/_site/en/na-midia': typeof SiteEnNaMidiaRoute
  '/_site/en/premiacoes': typeof SiteEnPremiacoesRoute
  '/_site/en/quem-somos': typeof SiteEnQuemSomosRoute
  '/_site/equipe/$slug': typeof SiteEquipeSlugRoute
  '/_site/es/blog': typeof SiteEsBlogRouteWithChildren
  '/_site/es/casos-de-sucesso': typeof SiteEsCasosDeSucessoRoute
  '/_site/es/contato': typeof SiteEsContatoRoute
  '/_site/es/na-midia': typeof SiteEsNaMidiaRoute
  '/_site/es/premiacoes': typeof SiteEsPremiacoesRoute
  '/_site/es/quem-somos': typeof SiteEsQuemSomosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_site/areas-de-atuacao/': typeof SiteAreasDeAtuacaoIndexRoute
  '/_site/en/': typeof SiteEnIndexRoute
  '/_site/equipe/': typeof SiteEquipeIndexRoute
  '/_site/es/': typeof SiteEsIndexRoute
  '/_authenticated/admin/posts/$id': typeof AuthenticatedAdminPostsIdRoute
  '/_authenticated/admin/posts/destaques': typeof AuthenticatedAdminPostsDestaquesRoute
  '/_authenticated/admin/posts/novo': typeof AuthenticatedAdminPostsNovoRoute
  '/_site/blog/autor/$slug': typeof SiteBlogAutorSlugRoute
  '/_site/blog/categoria/$slug': typeof SiteBlogCategoriaSlugRoute
  '/_site/blog/profissao/$slug': typeof SiteBlogProfissaoSlugRoute
  '/_site/blog/tag/$slug': typeof SiteBlogTagSlugRoute
  '/_site/en/blog/$slug': typeof SiteEnBlogSlugRoute
  '/_site/en/blog/search': typeof SiteEnBlogSearchRoute
  '/_site/en/equipe/$slug': typeof SiteEnEquipeSlugRoute
  '/_site/en/servicos/$slug': typeof SiteEnServicosSlugRoute
  '/_site/es/blog/$slug': typeof SiteEsBlogSlugRoute
  '/_site/es/blog/busqueda': typeof SiteEsBlogBusquedaRoute
  '/_site/es/equipe/$slug': typeof SiteEsEquipeSlugRoute
  '/_site/es/servicos/$slug': typeof SiteEsServicosSlugRoute
  '/_authenticated/admin/posts/': typeof AuthenticatedAdminPostsIndexRoute
  '/_site/en/equipe/': typeof SiteEnEquipeIndexRoute
  '/_site/en/servicos/': typeof SiteEnServicosIndexRoute
  '/_site/es/equipe/': typeof SiteEsEquipeIndexRoute
  '/_site/es/servicos/': typeof SiteEsServicosIndexRoute
  '/_site/en/blog/author/$slug': typeof SiteEnBlogAuthorSlugRoute
  '/_site/en/blog/category/$slug': typeof SiteEnBlogCategorySlugRoute
  '/_site/en/blog/profession/$slug': typeof SiteEnBlogProfessionSlugRoute
  '/_site/en/blog/tag/$slug': typeof SiteEnBlogTagSlugRoute
  '/_site/es/blog/autor/$slug': typeof SiteEsBlogAutorSlugRoute
  '/_site/es/blog/categoria/$slug': typeof SiteEsBlogCategoriaSlugRoute
  '/_site/es/blog/profesion/$slug': typeof SiteEsBlogProfesionSlugRoute
  '/_site/es/blog/tag/$slug': typeof SiteEsBlogTagSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/blog'
    | '/casos-de-sucesso'
    | '/contato'
    | '/na-midia'
    | '/premiacoes'
    | '/quem-somos'
    | '/admin/autores'
    | '/admin/categorias'
    | '/admin/equipe'
    | '/admin/midia'
    | '/admin/profissoes'
    | '/admin/seo'
    | '/admin/tags'
    | '/areas-de-atuacao/$slug'
    | '/blog/$slug'
    | '/blog/busca'
    | '/en/blog'
    | '/en/casos-de-sucesso'
    | '/en/contato'
    | '/en/na-midia'
    | '/en/premiacoes'
    | '/en/quem-somos'
    | '/equipe/$slug'
    | '/es/blog'
    | '/es/casos-de-sucesso'
    | '/es/contato'
    | '/es/na-midia'
    | '/es/premiacoes'
    | '/es/quem-somos'
    | '/admin/'
    | '/areas-de-atuacao/'
    | '/en/'
    | '/equipe/'
    | '/es/'
    | '/admin/posts/$id'
    | '/admin/posts/destaques'
    | '/admin/posts/novo'
    | '/blog/autor/$slug'
    | '/blog/categoria/$slug'
    | '/blog/profissao/$slug'
    | '/blog/tag/$slug'
    | '/en/blog/$slug'
    | '/en/blog/search'
    | '/en/equipe/$slug'
    | '/en/servicos/$slug'
    | '/es/blog/$slug'
    | '/es/blog/busqueda'
    | '/es/equipe/$slug'
    | '/es/servicos/$slug'
    | '/admin/posts/'
    | '/en/equipe/'
    | '/en/servicos/'
    | '/es/equipe/'
    | '/es/servicos/'
    | '/en/blog/author/$slug'
    | '/en/blog/category/$slug'
    | '/en/blog/profession/$slug'
    | '/en/blog/tag/$slug'
    | '/es/blog/autor/$slug'
    | '/es/blog/categoria/$slug'
    | '/es/blog/profesion/$slug'
    | '/es/blog/tag/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/blog'
    | '/casos-de-sucesso'
    | '/contato'
    | '/na-midia'
    | '/premiacoes'
    | '/quem-somos'
    | '/admin/autores'
    | '/admin/categorias'
    | '/admin/equipe'
    | '/admin/midia'
    | '/admin/profissoes'
    | '/admin/seo'
    | '/admin/tags'
    | '/areas-de-atuacao/$slug'
    | '/blog/$slug'
    | '/blog/busca'
    | '/en/blog'
    | '/en/casos-de-sucesso'
    | '/en/contato'
    | '/en/na-midia'
    | '/en/premiacoes'
    | '/en/quem-somos'
    | '/equipe/$slug'
    | '/es/blog'
    | '/es/casos-de-sucesso'
    | '/es/contato'
    | '/es/na-midia'
    | '/es/premiacoes'
    | '/es/quem-somos'
    | '/admin'
    | '/areas-de-atuacao'
    | '/en'
    | '/equipe'
    | '/es'
    | '/admin/posts/$id'
    | '/admin/posts/destaques'
    | '/admin/posts/novo'
    | '/blog/autor/$slug'
    | '/blog/categoria/$slug'
    | '/blog/profissao/$slug'
    | '/blog/tag/$slug'
    | '/en/blog/$slug'
    | '/en/blog/search'
    | '/en/equipe/$slug'
    | '/en/servicos/$slug'
    | '/es/blog/$slug'
    | '/es/blog/busqueda'
    | '/es/equipe/$slug'
    | '/es/servicos/$slug'
    | '/admin/posts'
    | '/en/equipe'
    | '/en/servicos'
    | '/es/equipe'
    | '/es/servicos'
    | '/en/blog/author/$slug'
    | '/en/blog/category/$slug'
    | '/en/blog/profession/$slug'
    | '/en/blog/tag/$slug'
    | '/es/blog/autor/$slug'
    | '/es/blog/categoria/$slug'
    | '/es/blog/profesion/$slug'
    | '/es/blog/tag/$slug'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_site'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_site/blog'
    | '/_site/casos-de-sucesso'
    | '/_site/contato'
    | '/_site/na-midia'
    | '/_site/premiacoes'
    | '/_site/quem-somos'
    | '/_site/'
    | '/_authenticated/admin/autores'
    | '/_authenticated/admin/categorias'
    | '/_authenticated/admin/equipe'
    | '/_authenticated/admin/midia'
    | '/_authenticated/admin/profissoes'
    | '/_authenticated/admin/seo'
    | '/_authenticated/admin/tags'
    | '/_site/areas-de-atuacao/$slug'
    | '/_site/blog/$slug'
    | '/_site/blog/busca'
    | '/_site/en/blog'
    | '/_site/en/casos-de-sucesso'
    | '/_site/en/contato'
    | '/_site/en/na-midia'
    | '/_site/en/premiacoes'
    | '/_site/en/quem-somos'
    | '/_site/equipe/$slug'
    | '/_site/es/blog'
    | '/_site/es/casos-de-sucesso'
    | '/_site/es/contato'
    | '/_site/es/na-midia'
    | '/_site/es/premiacoes'
    | '/_site/es/quem-somos'
    | '/_authenticated/admin/'
    | '/_site/areas-de-atuacao/'
    | '/_site/en/'
    | '/_site/equipe/'
    | '/_site/es/'
    | '/_authenticated/admin/posts/$id'
    | '/_authenticated/admin/posts/destaques'
    | '/_authenticated/admin/posts/novo'
    | '/_site/blog/autor/$slug'
    | '/_site/blog/categoria/$slug'
    | '/_site/blog/profissao/$slug'
    | '/_site/blog/tag/$slug'
    | '/_site/en/blog/$slug'
    | '/_site/en/blog/search'
    | '/_site/en/equipe/$slug'
    | '/_site/en/servicos/$slug'
    | '/_site/es/blog/$slug'
    | '/_site/es/blog/busqueda'
    | '/_site/es/equipe/$slug'
    | '/_site/es/servicos/$slug'
    | '/_authenticated/admin/posts/'
    | '/_site/en/equipe/'
    | '/_site/en/servicos/'
    | '/_site/es/equipe/'
    | '/_site/es/servicos/'
    | '/_site/en/blog/author/$slug'
    | '/_site/en/blog/category/$slug'
    | '/_site/en/blog/profession/$slug'
    | '/_site/en/blog/tag/$slug'
    | '/_site/es/blog/autor/$slug'
    | '/_site/es/blog/categoria/$slug'
    | '/_site/es/blog/profesion/$slug'
    | '/_site/es/blog/tag/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/quem-somos': {
      id: '/_site/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof SiteQuemSomosRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/premiacoes': {
      id: '/_site/premiacoes'
      path: '/premiacoes'
      fullPath: '/premiacoes'
      preLoaderRoute: typeof SitePremiacoesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/na-midia': {
      id: '/_site/na-midia'
      path: '/na-midia'
      fullPath: '/na-midia'
      preLoaderRoute: typeof SiteNaMidiaRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contato': {
      id: '/_site/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof SiteContatoRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/casos-de-sucesso': {
      id: '/_site/casos-de-sucesso'
      path: '/casos-de-sucesso'
      fullPath: '/casos-de-sucesso'
      preLoaderRoute: typeof SiteCasosDeSucessoRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog': {
      id: '/_site/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof SiteBlogRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_site/es/': {
      id: '/_site/es/'
      path: '/es'
      fullPath: '/es/'
      preLoaderRoute: typeof SiteEsIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/equipe/': {
      id: '/_site/equipe/'
      path: '/equipe'
      fullPath: '/equipe/'
      preLoaderRoute: typeof SiteEquipeIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/en/': {
      id: '/_site/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof SiteEnIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/areas-de-atuacao/': {
      id: '/_site/areas-de-atuacao/'
      path: '/areas-de-atuacao'
      fullPath: '/areas-de-atuacao/'
      preLoaderRoute: typeof SiteAreasDeAtuacaoIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_site/es/quem-somos': {
      id: '/_site/es/quem-somos'
      path: '/es/quem-somos'
      fullPath: '/es/quem-somos'
      preLoaderRoute: typeof SiteEsQuemSomosRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/es/premiacoes': {
      id: '/_site/es/premiacoes'
      path: '/es/premiacoes'
      fullPath: '/es/premiacoes'
      preLoaderRoute: typeof SiteEsPremiacoesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/es/na-midia': {
      id: '/_site/es/na-midia'
      path: '/es/na-midia'
      fullPath: '/es/na-midia'
      preLoaderRoute: typeof SiteEsNaMidiaRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/es/contato': {
      id: '/_site/es/contato'
      path: '/es/contato'
      fullPath: '/es/contato'
      preLoaderRoute: typeof SiteEsContatoRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/es/casos-de-sucesso': {
      id: '/_site/es/casos-de-sucesso'
      path: '/es/casos-de-sucesso'
      fullPath: '/es/casos-de-sucesso'
      preLoaderRoute: typeof SiteEsCasosDeSucessoRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/es/blog': {
      id: '/_site/es/blog'
      path: '/es/blog'
      fullPath: '/es/blog'
      preLoaderRoute: typeof SiteEsBlogRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/equipe/$slug': {
      id: '/_site/equipe/$slug'
      path: '/equipe/$slug'
      fullPath: '/equipe/$slug'
      preLoaderRoute: typeof SiteEquipeSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/en/quem-somos': {
      id: '/_site/en/quem-somos'
      path: '/en/quem-somos'
      fullPath: '/en/quem-somos'
      preLoaderRoute: typeof SiteEnQuemSomosRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/en/premiacoes': {
      id: '/_site/en/premiacoes'
      path: '/en/premiacoes'
      fullPath: '/en/premiacoes'
      preLoaderRoute: typeof SiteEnPremiacoesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/en/na-midia': {
      id: '/_site/en/na-midia'
      path: '/en/na-midia'
      fullPath: '/en/na-midia'
      preLoaderRoute: typeof SiteEnNaMidiaRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/en/contato': {
      id: '/_site/en/contato'
      path: '/en/contato'
      fullPath: '/en/contato'
      preLoaderRoute: typeof SiteEnContatoRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/en/casos-de-sucesso': {
      id: '/_site/en/casos-de-sucesso'
      path: '/en/casos-de-sucesso'
      fullPath: '/en/casos-de-sucesso'
      preLoaderRoute: typeof SiteEnCasosDeSucessoRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/en/blog': {
      id: '/_site/en/blog'
      path: '/en/blog'
      fullPath: '/en/blog'
      preLoaderRoute: typeof SiteEnBlogRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog/busca': {
      id: '/_site/blog/busca'
      path: '/busca'
      fullPath: '/blog/busca'
      preLoaderRoute: typeof SiteBlogBuscaRouteImport
      parentRoute: typeof SiteBlogRoute
    }
    '/_site/blog/$slug': {
      id: '/_site/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof SiteBlogSlugRouteImport
      parentRoute: typeof SiteBlogRoute
    }
    '/_site/areas-de-atuacao/$slug': {
      id: '/_site/areas-de-atuacao/$slug'
      path: '/areas-de-atuacao/$slug'
      fullPath: '/areas-de-atuacao/$slug'
      preLoaderRoute: typeof SiteAreasDeAtuacaoSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_authenticated/admin/tags': {
      id: '/_authenticated/admin/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AuthenticatedAdminTagsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/seo': {
      id: '/_authenticated/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AuthenticatedAdminSeoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/profissoes': {
      id: '/_authenticated/admin/profissoes'
      path: '/profissoes'
      fullPath: '/admin/profissoes'
      preLoaderRoute: typeof AuthenticatedAdminProfissoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/midia': {
      id: '/_authenticated/admin/midia'
      path: '/midia'
      fullPath: '/admin/midia'
      preLoaderRoute: typeof AuthenticatedAdminMidiaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/equipe': {
      id: '/_authenticated/admin/equipe'
      path: '/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof AuthenticatedAdminEquipeRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/categorias': {
      id: '/_authenticated/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AuthenticatedAdminCategoriasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/autores': {
      id: '/_authenticated/admin/autores'
      path: '/autores'
      fullPath: '/admin/autores'
      preLoaderRoute: typeof AuthenticatedAdminAutoresRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_site/es/servicos/': {
      id: '/_site/es/servicos/'
      path: '/es/servicos'
      fullPath: '/es/servicos/'
      preLoaderRoute: typeof SiteEsServicosIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/es/equipe/': {
      id: '/_site/es/equipe/'
      path: '/es/equipe'
      fullPath: '/es/equipe/'
      preLoaderRoute: typeof SiteEsEquipeIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/en/servicos/': {
      id: '/_site/en/servicos/'
      path: '/en/servicos'
      fullPath: '/en/servicos/'
      preLoaderRoute: typeof SiteEnServicosIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/en/equipe/': {
      id: '/_site/en/equipe/'
      path: '/en/equipe'
      fullPath: '/en/equipe/'
      preLoaderRoute: typeof SiteEnEquipeIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_authenticated/admin/posts/': {
      id: '/_authenticated/admin/posts/'
      path: '/posts'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AuthenticatedAdminPostsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_site/es/servicos/$slug': {
      id: '/_site/es/servicos/$slug'
      path: '/es/servicos/$slug'
      fullPath: '/es/servicos/$slug'
      preLoaderRoute: typeof SiteEsServicosSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/es/equipe/$slug': {
      id: '/_site/es/equipe/$slug'
      path: '/es/equipe/$slug'
      fullPath: '/es/equipe/$slug'
      preLoaderRoute: typeof SiteEsEquipeSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/es/blog/busqueda': {
      id: '/_site/es/blog/busqueda'
      path: '/busqueda'
      fullPath: '/es/blog/busqueda'
      preLoaderRoute: typeof SiteEsBlogBusquedaRouteImport
      parentRoute: typeof SiteEsBlogRoute
    }
    '/_site/es/blog/$slug': {
      id: '/_site/es/blog/$slug'
      path: '/$slug'
      fullPath: '/es/blog/$slug'
      preLoaderRoute: typeof SiteEsBlogSlugRouteImport
      parentRoute: typeof SiteEsBlogRoute
    }
    '/_site/en/servicos/$slug': {
      id: '/_site/en/servicos/$slug'
      path: '/en/servicos/$slug'
      fullPath: '/en/servicos/$slug'
      preLoaderRoute: typeof SiteEnServicosSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/en/equipe/$slug': {
      id: '/_site/en/equipe/$slug'
      path: '/en/equipe/$slug'
      fullPath: '/en/equipe/$slug'
      preLoaderRoute: typeof SiteEnEquipeSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/en/blog/search': {
      id: '/_site/en/blog/search'
      path: '/search'
      fullPath: '/en/blog/search'
      preLoaderRoute: typeof SiteEnBlogSearchRouteImport
      parentRoute: typeof SiteEnBlogRoute
    }
    '/_site/en/blog/$slug': {
      id: '/_site/en/blog/$slug'
      path: '/$slug'
      fullPath: '/en/blog/$slug'
      preLoaderRoute: typeof SiteEnBlogSlugRouteImport
      parentRoute: typeof SiteEnBlogRoute
    }
    '/_site/blog/tag/$slug': {
      id: '/_site/blog/tag/$slug'
      path: '/tag/$slug'
      fullPath: '/blog/tag/$slug'
      preLoaderRoute: typeof SiteBlogTagSlugRouteImport
      parentRoute: typeof SiteBlogRoute
    }
    '/_site/blog/profissao/$slug': {
      id: '/_site/blog/profissao/$slug'
      path: '/profissao/$slug'
      fullPath: '/blog/profissao/$slug'
      preLoaderRoute: typeof SiteBlogProfissaoSlugRouteImport
      parentRoute: typeof SiteBlogRoute
    }
    '/_site/blog/categoria/$slug': {
      id: '/_site/blog/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/blog/categoria/$slug'
      preLoaderRoute: typeof SiteBlogCategoriaSlugRouteImport
      parentRoute: typeof SiteBlogRoute
    }
    '/_site/blog/autor/$slug': {
      id: '/_site/blog/autor/$slug'
      path: '/autor/$slug'
      fullPath: '/blog/autor/$slug'
      preLoaderRoute: typeof SiteBlogAutorSlugRouteImport
      parentRoute: typeof SiteBlogRoute
    }
    '/_authenticated/admin/posts/novo': {
      id: '/_authenticated/admin/posts/novo'
      path: '/posts/novo'
      fullPath: '/admin/posts/novo'
      preLoaderRoute: typeof AuthenticatedAdminPostsNovoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/posts/destaques': {
      id: '/_authenticated/admin/posts/destaques'
      path: '/posts/destaques'
      fullPath: '/admin/posts/destaques'
      preLoaderRoute: typeof AuthenticatedAdminPostsDestaquesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/posts/$id': {
      id: '/_authenticated/admin/posts/$id'
      path: '/posts/$id'
      fullPath: '/admin/posts/$id'
      preLoaderRoute: typeof AuthenticatedAdminPostsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_site/es/blog/tag/$slug': {
      id: '/_site/es/blog/tag/$slug'
      path: '/tag/$slug'
      fullPath: '/es/blog/tag/$slug'
      preLoaderRoute: typeof SiteEsBlogTagSlugRouteImport
      parentRoute: typeof SiteEsBlogRoute
    }
    '/_site/es/blog/profesion/$slug': {
      id: '/_site/es/blog/profesion/$slug'
      path: '/profesion/$slug'
      fullPath: '/es/blog/profesion/$slug'
      preLoaderRoute: typeof SiteEsBlogProfesionSlugRouteImport
      parentRoute: typeof SiteEsBlogRoute
    }
    '/_site/es/blog/categoria/$slug': {
      id: '/_site/es/blog/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/es/blog/categoria/$slug'
      preLoaderRoute: typeof SiteEsBlogCategoriaSlugRouteImport
      parentRoute: typeof SiteEsBlogRoute
    }
    '/_site/es/blog/autor/$slug': {
      id: '/_site/es/blog/autor/$slug'
      path: '/autor/$slug'
      fullPath: '/es/blog/autor/$slug'
      preLoaderRoute: typeof SiteEsBlogAutorSlugRouteImport
      parentRoute: typeof SiteEsBlogRoute
    }
    '/_site/en/blog/tag/$slug': {
      id: '/_site/en/blog/tag/$slug'
      path: '/tag/$slug'
      fullPath: '/en/blog/tag/$slug'
      preLoaderRoute: typeof SiteEnBlogTagSlugRouteImport
      parentRoute: typeof SiteEnBlogRoute
    }
    '/_site/en/blog/profession/$slug': {
      id: '/_site/en/blog/profession/$slug'
      path: '/profession/$slug'
      fullPath: '/en/blog/profession/$slug'
      preLoaderRoute: typeof SiteEnBlogProfessionSlugRouteImport
      parentRoute: typeof SiteEnBlogRoute
    }
    '/_site/en/blog/category/$slug': {
      id: '/_site/en/blog/category/$slug'
      path: '/category/$slug'
      fullPath: '/en/blog/category/$slug'
      preLoaderRoute: typeof SiteEnBlogCategorySlugRouteImport
      parentRoute: typeof SiteEnBlogRoute
    }
    '/_site/en/blog/author/$slug': {
      id: '/_site/en/blog/author/$slug'
      path: '/author/$slug'
      fullPath: '/en/blog/author/$slug'
      preLoaderRoute: typeof SiteEnBlogAuthorSlugRouteImport
      parentRoute: typeof SiteEnBlogRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAutoresRoute: typeof AuthenticatedAdminAutoresRoute
  AuthenticatedAdminCategoriasRoute: typeof AuthenticatedAdminCategoriasRoute
  AuthenticatedAdminEquipeRoute: typeof AuthenticatedAdminEquipeRoute
  AuthenticatedAdminMidiaRoute: typeof AuthenticatedAdminMidiaRoute
  AuthenticatedAdminProfissoesRoute: typeof AuthenticatedAdminProfissoesRoute
  AuthenticatedAdminSeoRoute: typeof AuthenticatedAdminSeoRoute
  AuthenticatedAdminTagsRoute: typeof AuthenticatedAdminTagsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminPostsIdRoute: typeof AuthenticatedAdminPostsIdRoute
  AuthenticatedAdminPostsDestaquesRoute: typeof AuthenticatedAdminPostsDestaquesRoute
  AuthenticatedAdminPostsNovoRoute: typeof AuthenticatedAdminPostsNovoRoute
  AuthenticatedAdminPostsIndexRoute: typeof AuthenticatedAdminPostsIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAutoresRoute: AuthenticatedAdminAutoresRoute,
    AuthenticatedAdminCategoriasRoute: AuthenticatedAdminCategoriasRoute,
    AuthenticatedAdminEquipeRoute: AuthenticatedAdminEquipeRoute,
    AuthenticatedAdminMidiaRoute: AuthenticatedAdminMidiaRoute,
    AuthenticatedAdminProfissoesRoute: AuthenticatedAdminProfissoesRoute,
    AuthenticatedAdminSeoRoute: AuthenticatedAdminSeoRoute,
    AuthenticatedAdminTagsRoute: AuthenticatedAdminTagsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminPostsIdRoute: AuthenticatedAdminPostsIdRoute,
    AuthenticatedAdminPostsDestaquesRoute:
      AuthenticatedAdminPostsDestaquesRoute,
    AuthenticatedAdminPostsNovoRoute: AuthenticatedAdminPostsNovoRoute,
    AuthenticatedAdminPostsIndexRoute: AuthenticatedAdminPostsIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SiteBlogRouteChildren {
  SiteBlogSlugRoute: typeof SiteBlogSlugRoute
  SiteBlogBuscaRoute: typeof SiteBlogBuscaRoute
  SiteBlogAutorSlugRoute: typeof SiteBlogAutorSlugRoute
  SiteBlogCategoriaSlugRoute: typeof SiteBlogCategoriaSlugRoute
  SiteBlogProfissaoSlugRoute: typeof SiteBlogProfissaoSlugRoute
  SiteBlogTagSlugRoute: typeof SiteBlogTagSlugRoute
}

const SiteBlogRouteChildren: SiteBlogRouteChildren = {
  SiteBlogSlugRoute: SiteBlogSlugRoute,
  SiteBlogBuscaRoute: SiteBlogBuscaRoute,
  SiteBlogAutorSlugRoute: SiteBlogAutorSlugRoute,
  SiteBlogCategoriaSlugRoute: SiteBlogCategoriaSlugRoute,
  SiteBlogProfissaoSlugRoute: SiteBlogProfissaoSlugRoute,
  SiteBlogTagSlugRoute: SiteBlogTagSlugRoute,
}

const SiteBlogRouteWithChildren = SiteBlogRoute._addFileChildren(
  SiteBlogRouteChildren,
)

interface SiteEnBlogRouteChildren {
  SiteEnBlogSlugRoute: typeof SiteEnBlogSlugRoute
  SiteEnBlogSearchRoute: typeof SiteEnBlogSearchRoute
  SiteEnBlogAuthorSlugRoute: typeof SiteEnBlogAuthorSlugRoute
  SiteEnBlogCategorySlugRoute: typeof SiteEnBlogCategorySlugRoute
  SiteEnBlogProfessionSlugRoute: typeof SiteEnBlogProfessionSlugRoute
  SiteEnBlogTagSlugRoute: typeof SiteEnBlogTagSlugRoute
}

const SiteEnBlogRouteChildren: SiteEnBlogRouteChildren = {
  SiteEnBlogSlugRoute: SiteEnBlogSlugRoute,
  SiteEnBlogSearchRoute: SiteEnBlogSearchRoute,
  SiteEnBlogAuthorSlugRoute: SiteEnBlogAuthorSlugRoute,
  SiteEnBlogCategorySlugRoute: SiteEnBlogCategorySlugRoute,
  SiteEnBlogProfessionSlugRoute: SiteEnBlogProfessionSlugRoute,
  SiteEnBlogTagSlugRoute: SiteEnBlogTagSlugRoute,
}

const SiteEnBlogRouteWithChildren = SiteEnBlogRoute._addFileChildren(
  SiteEnBlogRouteChildren,
)

interface SiteEsBlogRouteChildren {
  SiteEsBlogSlugRoute: typeof SiteEsBlogSlugRoute
  SiteEsBlogBusquedaRoute: typeof SiteEsBlogBusquedaRoute
  SiteEsBlogAutorSlugRoute: typeof SiteEsBlogAutorSlugRoute
  SiteEsBlogCategoriaSlugRoute: typeof SiteEsBlogCategoriaSlugRoute
  SiteEsBlogProfesionSlugRoute: typeof SiteEsBlogProfesionSlugRoute
  SiteEsBlogTagSlugRoute: typeof SiteEsBlogTagSlugRoute
}

const SiteEsBlogRouteChildren: SiteEsBlogRouteChildren = {
  SiteEsBlogSlugRoute: SiteEsBlogSlugRoute,
  SiteEsBlogBusquedaRoute: SiteEsBlogBusquedaRoute,
  SiteEsBlogAutorSlugRoute: SiteEsBlogAutorSlugRoute,
  SiteEsBlogCategoriaSlugRoute: SiteEsBlogCategoriaSlugRoute,
  SiteEsBlogProfesionSlugRoute: SiteEsBlogProfesionSlugRoute,
  SiteEsBlogTagSlugRoute: SiteEsBlogTagSlugRoute,
}

const SiteEsBlogRouteWithChildren = SiteEsBlogRoute._addFileChildren(
  SiteEsBlogRouteChildren,
)

interface SiteRouteChildren {
  SiteBlogRoute: typeof SiteBlogRouteWithChildren
  SiteCasosDeSucessoRoute: typeof SiteCasosDeSucessoRoute
  SiteContatoRoute: typeof SiteContatoRoute
  SiteNaMidiaRoute: typeof SiteNaMidiaRoute
  SitePremiacoesRoute: typeof SitePremiacoesRoute
  SiteQuemSomosRoute: typeof SiteQuemSomosRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteAreasDeAtuacaoSlugRoute: typeof SiteAreasDeAtuacaoSlugRoute
  SiteEnBlogRoute: typeof SiteEnBlogRouteWithChildren
  SiteEnCasosDeSucessoRoute: typeof SiteEnCasosDeSucessoRoute
  SiteEnContatoRoute: typeof SiteEnContatoRoute
  SiteEnNaMidiaRoute: typeof SiteEnNaMidiaRoute
  SiteEnPremiacoesRoute: typeof SiteEnPremiacoesRoute
  SiteEnQuemSomosRoute: typeof SiteEnQuemSomosRoute
  SiteEquipeSlugRoute: typeof SiteEquipeSlugRoute
  SiteEsBlogRoute: typeof SiteEsBlogRouteWithChildren
  SiteEsCasosDeSucessoRoute: typeof SiteEsCasosDeSucessoRoute
  SiteEsContatoRoute: typeof SiteEsContatoRoute
  SiteEsNaMidiaRoute: typeof SiteEsNaMidiaRoute
  SiteEsPremiacoesRoute: typeof SiteEsPremiacoesRoute
  SiteEsQuemSomosRoute: typeof SiteEsQuemSomosRoute
  SiteAreasDeAtuacaoIndexRoute: typeof SiteAreasDeAtuacaoIndexRoute
  SiteEnIndexRoute: typeof SiteEnIndexRoute
  SiteEquipeIndexRoute: typeof SiteEquipeIndexRoute
  SiteEsIndexRoute: typeof SiteEsIndexRoute
  SiteEnEquipeSlugRoute: typeof SiteEnEquipeSlugRoute
  SiteEnServicosSlugRoute: typeof SiteEnServicosSlugRoute
  SiteEsEquipeSlugRoute: typeof SiteEsEquipeSlugRoute
  SiteEsServicosSlugRoute: typeof SiteEsServicosSlugRoute
  SiteEnEquipeIndexRoute: typeof SiteEnEquipeIndexRoute
  SiteEnServicosIndexRoute: typeof SiteEnServicosIndexRoute
  SiteEsEquipeIndexRoute: typeof SiteEsEquipeIndexRoute
  SiteEsServicosIndexRoute: typeof SiteEsServicosIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteBlogRoute: SiteBlogRouteWithChildren,
  SiteCasosDeSucessoRoute: SiteCasosDeSucessoRoute,
  SiteContatoRoute: SiteContatoRoute,
  SiteNaMidiaRoute: SiteNaMidiaRoute,
  SitePremiacoesRoute: SitePremiacoesRoute,
  SiteQuemSomosRoute: SiteQuemSomosRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteAreasDeAtuacaoSlugRoute: SiteAreasDeAtuacaoSlugRoute,
  SiteEnBlogRoute: SiteEnBlogRouteWithChildren,
  SiteEnCasosDeSucessoRoute: SiteEnCasosDeSucessoRoute,
  SiteEnContatoRoute: SiteEnContatoRoute,
  SiteEnNaMidiaRoute: SiteEnNaMidiaRoute,
  SiteEnPremiacoesRoute: SiteEnPremiacoesRoute,
  SiteEnQuemSomosRoute: SiteEnQuemSomosRoute,
  SiteEquipeSlugRoute: SiteEquipeSlugRoute,
  SiteEsBlogRoute: SiteEsBlogRouteWithChildren,
  SiteEsCasosDeSucessoRoute: SiteEsCasosDeSucessoRoute,
  SiteEsContatoRoute: SiteEsContatoRoute,
  SiteEsNaMidiaRoute: SiteEsNaMidiaRoute,
  SiteEsPremiacoesRoute: SiteEsPremiacoesRoute,
  SiteEsQuemSomosRoute: SiteEsQuemSomosRoute,
  SiteAreasDeAtuacaoIndexRoute: SiteAreasDeAtuacaoIndexRoute,
  SiteEnIndexRoute: SiteEnIndexRoute,
  SiteEquipeIndexRoute: SiteEquipeIndexRoute,
  SiteEsIndexRoute: SiteEsIndexRoute,
  SiteEnEquipeSlugRoute: SiteEnEquipeSlugRoute,
  SiteEnServicosSlugRoute: SiteEnServicosSlugRoute,
  SiteEsEquipeSlugRoute: SiteEsEquipeSlugRoute,
  SiteEsServicosSlugRoute: SiteEsServicosSlugRoute,
  SiteEnEquipeIndexRoute: SiteEnEquipeIndexRoute,
  SiteEnServicosIndexRoute: SiteEnServicosIndexRoute,
  SiteEsEquipeIndexRoute: SiteEsEquipeIndexRoute,
  SiteEsServicosIndexRoute: SiteEsServicosIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
